/**
 * Universal Knowledge Platform — Seed Script
 * Seeds: exams, subjects, curricula, all 80 JEE chapters with weightage/difficulty/study plan data
 */
import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// ─── Helper ───────────────────────────────────────────────────────────────────
async function upsert(table, data, uniqueKey) {
  const keys = Object.keys(data);
  const vals = Object.values(data);
  const placeholders = keys.map(() => '?').join(', ');
  const updates = keys.filter(k => k !== uniqueKey).map(k => `\`${k}\` = VALUES(\`${k}\`)`).join(', ');
  const sql = `INSERT INTO \`${table}\` (\`${keys.join('`, `')}\`) VALUES (${placeholders}) ON DUPLICATE KEY UPDATE ${updates}`;
  await conn.execute(sql, vals.map(v => typeof v === 'object' && v !== null ? JSON.stringify(v) : v));
}

// ─── 1. Exams ─────────────────────────────────────────────────────────────────
console.log('Seeding exams...');
await upsert('exams', {
  examId: 'jee_main', name: 'JEE Main', fullName: 'Joint Entrance Examination Main',
  category: 'engineering', conductingBody: 'NTA (National Testing Agency)', country: 'India',
  description: 'National level entrance exam for admission to NITs, IIITs, and CFTIs. Conducted twice a year.',
  officialUrl: 'https://jeemain.nta.nic.in', isActive: true
}, 'examId');

await upsert('exams', {
  examId: 'jee_advanced', name: 'JEE Advanced', fullName: 'Joint Entrance Examination Advanced',
  category: 'engineering', conductingBody: 'IITs (Joint Admission Board)', country: 'India',
  description: 'Highly competitive exam for admission to IITs. Only top 2.5 lakh JEE Main qualifiers are eligible.',
  officialUrl: 'https://jeeadv.ac.in', isActive: true
}, 'examId');

// ─── 2. Subjects ──────────────────────────────────────────────────────────────
console.log('Seeding subjects...');
await upsert('subjects', { subjectId: 'physics', name: 'Physics', shortName: 'PHY', iconName: 'atom', colorHex: '#3B82F6', description: 'Classical Mechanics, Electromagnetism, Optics, Modern Physics and more.', isActive: true }, 'subjectId');
await upsert('subjects', { subjectId: 'chemistry', name: 'Chemistry', shortName: 'CHE', iconName: 'flask-conical', colorHex: '#10B981', description: 'Physical, Organic and Inorganic Chemistry covering NCERT Class 11 & 12.', isActive: true }, 'subjectId');
await upsert('subjects', { subjectId: 'mathematics', name: 'Mathematics', shortName: 'MAT', iconName: 'calculator', colorHex: '#F59E0B', description: 'Algebra, Calculus, Coordinate Geometry, Vectors, Probability and more.', isActive: true }, 'subjectId');

// ─── 3. Curricula ─────────────────────────────────────────────────────────────
console.log('Seeding curricula...');
await upsert('curricula', { curriculumId: 'ncert_class11', name: 'NCERT Class 11', board: 'NCERT/CBSE', gradeLevel: 'Class 11', gradeLevelNum: 11, country: 'India', description: 'Foundation year — concept building. Covers Class 11 NCERT syllabus.', isActive: true }, 'curriculumId');
await upsert('curricula', { curriculumId: 'ncert_class12', name: 'NCERT Class 12', board: 'NCERT/CBSE', gradeLevel: 'Class 12', gradeLevelNum: 12, country: 'India', description: 'Scoring year — problem solving and speed. Covers Class 12 NCERT syllabus.', isActive: true }, 'curriculumId');

// ─── 4. Exam-Subject Mappings ─────────────────────────────────────────────────
console.log('Seeding exam-subject mappings...');
const examSubjects = [
  { examId: 'jee_main', subjectId: 'physics', totalChapters: 25, weightagePercent: 33.3, sortOrder: 1 },
  { examId: 'jee_main', subjectId: 'chemistry', totalChapters: 28, weightagePercent: 33.3, sortOrder: 2 },
  { examId: 'jee_main', subjectId: 'mathematics', totalChapters: 27, weightagePercent: 33.3, sortOrder: 3 },
  { examId: 'jee_advanced', subjectId: 'physics', totalChapters: 25, weightagePercent: 33.3, sortOrder: 1 },
  { examId: 'jee_advanced', subjectId: 'chemistry', totalChapters: 28, weightagePercent: 33.3, sortOrder: 2 },
  { examId: 'jee_advanced', subjectId: 'mathematics', totalChapters: 27, weightagePercent: 33.3, sortOrder: 3 },
];
for (const es of examSubjects) {
  await conn.execute(`INSERT INTO exam_subjects (examId, subjectId, totalChapters, weightagePercent, sortOrder) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE totalChapters=VALUES(totalChapters)`, [es.examId, es.subjectId, es.totalChapters, es.weightagePercent, es.sortOrder]);
}

// ─── 5. Chapters ──────────────────────────────────────────────────────────────
console.log('Seeding all 80 chapters...');

const chapters = [
  // ═══════════════════════════════════════════════════════════════════════
  // PHYSICS — Class 11 (12 chapters)
  // ═══════════════════════════════════════════════════════════════════════
  { chapterId: 'PHY_C11_01', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 1, title: 'Units & Measurements', slug: 'units-and-measurements', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 1, tags: JSON.stringify(['units','dimensions','errors','experiments']), keyTopics: JSON.stringify(['SI units','Dimensional analysis','Significant figures','Errors in measurement','Vernier caliper','Screw gauge']), learningObjectives: JSON.stringify(['Understand SI system','Apply dimensional analysis','Calculate measurement errors']), prerequisites: JSON.stringify([]) },
  { chapterId: 'PHY_C11_02', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 2, title: 'Kinematics', slug: 'kinematics', difficultyLevel: 'intermediate', estimatedStudyHours: 15, sortOrder: 2, tags: JSON.stringify(['motion','velocity','acceleration','projectile']), keyTopics: JSON.stringify(['Distance vs displacement','Velocity & acceleration','Equations of motion','Projectile motion','Relative motion','Graphs of motion']), learningObjectives: JSON.stringify(['Analyze 1D and 2D motion','Solve projectile problems','Interpret motion graphs']), prerequisites: JSON.stringify(['PHY_C11_01']) },
  { chapterId: 'PHY_C11_03', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 3, title: 'Laws of Motion', slug: 'laws-of-motion', difficultyLevel: 'intermediate', estimatedStudyHours: 18, sortOrder: 3, tags: JSON.stringify(['newton','force','friction','momentum']), keyTopics: JSON.stringify(['Newton\'s 3 laws','Free body diagrams','Friction (static & kinetic)','Circular motion','Pseudo forces','Impulse & momentum']), learningObjectives: JSON.stringify(['Apply Newton\'s laws','Solve friction problems','Analyze circular motion']), prerequisites: JSON.stringify(['PHY_C11_02']) },
  { chapterId: 'PHY_C11_04', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 4, title: 'Work, Energy & Power', slug: 'work-energy-power', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 4, tags: JSON.stringify(['work','energy','power','conservation']), keyTopics: JSON.stringify(['Work-energy theorem','Kinetic & potential energy','Conservation of energy','Power','Elastic & inelastic collisions','Spring potential energy']), learningObjectives: JSON.stringify(['Apply work-energy theorem','Solve collision problems','Use energy conservation']), prerequisites: JSON.stringify(['PHY_C11_03']) },
  { chapterId: 'PHY_C11_05', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 5, title: 'Rotational Motion', slug: 'rotational-motion', difficultyLevel: 'advanced', estimatedStudyHours: 22, sortOrder: 5, tags: JSON.stringify(['rotation','torque','moment of inertia','angular momentum']), keyTopics: JSON.stringify(['Torque & angular momentum','Moment of inertia','Parallel & perpendicular axis theorems','Rolling motion','Angular kinematics','Conservation of angular momentum']), learningObjectives: JSON.stringify(['Calculate moment of inertia','Apply rotational dynamics','Solve rolling motion problems']), prerequisites: JSON.stringify(['PHY_C11_04']) },
  { chapterId: 'PHY_C11_06', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 6, title: 'Gravitation', slug: 'gravitation', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 6, tags: JSON.stringify(['gravity','orbital motion','satellites','escape velocity']), keyTopics: JSON.stringify(['Newton\'s law of gravitation','Gravitational field & potential','Orbital velocity','Escape velocity','Kepler\'s laws','Satellites & geostationary orbits']), learningObjectives: JSON.stringify(['Apply gravitational laws','Calculate orbital parameters','Understand satellite motion']), prerequisites: JSON.stringify(['PHY_C11_03']) },
  { chapterId: 'PHY_C11_07', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 7, title: 'Properties of Solids & Fluids', slug: 'properties-solids-fluids', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 7, tags: JSON.stringify(['elasticity','viscosity','surface tension','fluid mechanics']), keyTopics: JSON.stringify(['Stress & strain','Young\'s modulus','Bernoulli\'s theorem','Viscosity & Stokes law','Surface tension','Capillarity']), learningObjectives: JSON.stringify(['Understand elastic properties','Apply Bernoulli\'s theorem','Solve surface tension problems']), prerequisites: JSON.stringify(['PHY_C11_03']) },
  { chapterId: 'PHY_C11_08', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 8, title: 'Thermodynamics', slug: 'thermodynamics', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 8, tags: JSON.stringify(['heat','temperature','entropy','carnot']), keyTopics: JSON.stringify(['Zeroth, First, Second laws','Internal energy','Isothermal & adiabatic processes','Carnot engine','Entropy','Heat engines & refrigerators']), learningObjectives: JSON.stringify(['Apply laws of thermodynamics','Calculate efficiency','Understand entropy']), prerequisites: JSON.stringify(['PHY_C11_07']) },
  { chapterId: 'PHY_C11_09', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 9, title: 'Kinetic Theory of Gases', slug: 'kinetic-theory-gases', difficultyLevel: 'intermediate', estimatedStudyHours: 10, sortOrder: 9, tags: JSON.stringify(['ideal gas','kinetic theory','rms speed','degrees of freedom']), keyTopics: JSON.stringify(['Ideal gas equation','Kinetic theory assumptions','RMS speed','Degrees of freedom','Law of equipartition','Mean free path']), learningObjectives: JSON.stringify(['Derive gas laws from kinetic theory','Calculate molecular speeds','Apply equipartition theorem']), prerequisites: JSON.stringify(['PHY_C11_08']) },
  { chapterId: 'PHY_C11_10', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 10, title: 'Oscillations (SHM)', slug: 'oscillations-shm', difficultyLevel: 'advanced', estimatedStudyHours: 16, sortOrder: 10, tags: JSON.stringify(['shm','pendulum','spring','resonance']), keyTopics: JSON.stringify(['Simple harmonic motion','Spring-mass system','Simple pendulum','Energy in SHM','Damped & forced oscillations','Resonance']), learningObjectives: JSON.stringify(['Analyze SHM mathematically','Calculate time periods','Understand resonance']), prerequisites: JSON.stringify(['PHY_C11_04','PHY_C11_05']) },
  { chapterId: 'PHY_C11_11', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 11, title: 'Waves', slug: 'waves', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 11, tags: JSON.stringify(['waves','sound','doppler','standing waves']), keyTopics: JSON.stringify(['Wave equation','Superposition principle','Standing waves','Beats','Doppler effect','Speed of sound']), learningObjectives: JSON.stringify(['Analyze wave properties','Solve Doppler problems','Understand standing waves']), prerequisites: JSON.stringify(['PHY_C11_10']) },
  { chapterId: 'PHY_C11_12', subjectId: 'physics', curriculumId: 'ncert_class11', chapterNo: 12, title: 'Thermal Properties of Matter', slug: 'thermal-properties-matter', difficultyLevel: 'foundation', estimatedStudyHours: 10, sortOrder: 12, tags: JSON.stringify(['heat transfer','calorimetry','expansion','radiation']), keyTopics: JSON.stringify(['Specific heat capacity','Latent heat','Thermal expansion','Conduction, convection, radiation','Newton\'s law of cooling','Stefan-Boltzmann law']), learningObjectives: JSON.stringify(['Calculate heat transfer','Apply calorimetry','Understand thermal expansion']), prerequisites: JSON.stringify(['PHY_C11_08']) },

  // ═══════════════════════════════════════════════════════════════════════
  // PHYSICS — Class 12 (13 chapters)
  // ═══════════════════════════════════════════════════════════════════════
  { chapterId: 'PHY_C12_01', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 1, title: 'Electrostatics', slug: 'electrostatics', difficultyLevel: 'intermediate', estimatedStudyHours: 18, sortOrder: 13, tags: JSON.stringify(['coulomb','electric field','potential','capacitor']), keyTopics: JSON.stringify(['Coulomb\'s law','Electric field & potential','Gauss\'s law','Capacitors & dielectrics','Electric dipole','Energy stored in capacitor']), learningObjectives: JSON.stringify(['Apply Coulomb\'s law','Use Gauss\'s law','Solve capacitor problems']), prerequisites: JSON.stringify(['PHY_C11_03']) },
  { chapterId: 'PHY_C12_02', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 2, title: 'Current Electricity', slug: 'current-electricity', difficultyLevel: 'intermediate', estimatedStudyHours: 18, sortOrder: 14, tags: JSON.stringify(['ohm','resistance','kirchhoff','wheatstone']), keyTopics: JSON.stringify(['Ohm\'s law','Kirchhoff\'s laws','Wheatstone bridge','Potentiometer','Drift velocity','Temperature dependence of resistance']), learningObjectives: JSON.stringify(['Apply Kirchhoff\'s laws','Solve circuit problems','Use Wheatstone bridge']), prerequisites: JSON.stringify(['PHY_C12_01']) },
  { chapterId: 'PHY_C12_03', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 3, title: 'Magnetic Effects of Current', slug: 'magnetic-effects-current', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 15, tags: JSON.stringify(['biot-savart','ampere','lorentz','solenoid']), keyTopics: JSON.stringify(['Biot-Savart law','Ampere\'s law','Force on current-carrying conductor','Torque on current loop','Solenoid & toroid','Moving coil galvanometer']), learningObjectives: JSON.stringify(['Apply Biot-Savart law','Calculate magnetic fields','Understand galvanometer']), prerequisites: JSON.stringify(['PHY_C12_02']) },
  { chapterId: 'PHY_C12_04', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 4, title: 'Magnetism & Matter', slug: 'magnetism-matter', difficultyLevel: 'intermediate', estimatedStudyHours: 10, sortOrder: 16, tags: JSON.stringify(['magnetism','diamagnetic','paramagnetic','ferromagnetic']), keyTopics: JSON.stringify(['Bar magnet','Earth\'s magnetism','Magnetic properties of materials','Hysteresis','Curie\'s law','Magnetic susceptibility']), learningObjectives: JSON.stringify(['Classify magnetic materials','Understand Earth\'s magnetism','Apply Curie\'s law']), prerequisites: JSON.stringify(['PHY_C12_03']) },
  { chapterId: 'PHY_C12_05', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 5, title: 'Electromagnetic Induction (EMI)', slug: 'electromagnetic-induction', difficultyLevel: 'advanced', estimatedStudyHours: 18, sortOrder: 17, tags: JSON.stringify(['faraday','lenz','inductance','eddy currents']), keyTopics: JSON.stringify(['Faraday\'s laws','Lenz\'s law','Motional EMF','Self & mutual inductance','Eddy currents','AC generator']), learningObjectives: JSON.stringify(['Apply Faraday\'s law','Calculate induced EMF','Understand inductance']), prerequisites: JSON.stringify(['PHY_C12_03','PHY_C12_04']) },
  { chapterId: 'PHY_C12_06', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 6, title: 'Alternating Current (AC)', slug: 'alternating-current', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 18, tags: JSON.stringify(['ac','impedance','resonance','transformer']), keyTopics: JSON.stringify(['AC circuits (R, L, C)','Impedance & reactance','Resonance in LC circuit','Power factor','Transformer','LC oscillations']), learningObjectives: JSON.stringify(['Analyze AC circuits','Calculate impedance','Understand resonance']), prerequisites: JSON.stringify(['PHY_C12_05']) },
  { chapterId: 'PHY_C12_07', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 7, title: 'Electromagnetic Waves', slug: 'electromagnetic-waves', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 19, tags: JSON.stringify(['em waves','spectrum','maxwell','displacement current']), keyTopics: JSON.stringify(['Maxwell\'s equations','Displacement current','EM spectrum','Properties of EM waves','Speed of light']), learningObjectives: JSON.stringify(['Understand EM wave properties','Know EM spectrum','Apply Maxwell\'s equations']), prerequisites: JSON.stringify(['PHY_C12_06']) },
  { chapterId: 'PHY_C12_08', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 8, title: 'Ray Optics', slug: 'ray-optics', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 20, tags: JSON.stringify(['reflection','refraction','lens','mirror']), keyTopics: JSON.stringify(['Reflection & refraction','Snell\'s law','Total internal reflection','Lenses & mirrors','Lens maker\'s equation','Optical instruments']), learningObjectives: JSON.stringify(['Apply mirror/lens formulas','Solve refraction problems','Understand optical instruments']), prerequisites: JSON.stringify(['PHY_C12_07']) },
  { chapterId: 'PHY_C12_09', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 9, title: 'Wave Optics', slug: 'wave-optics', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 21, tags: JSON.stringify(['interference','diffraction','polarization','young']), keyTopics: JSON.stringify(['Huygens principle','Young\'s double slit experiment','Interference','Diffraction','Polarization','Resolving power']), learningObjectives: JSON.stringify(['Analyze interference patterns','Calculate diffraction','Understand polarization']), prerequisites: JSON.stringify(['PHY_C12_08','PHY_C11_11']) },
  { chapterId: 'PHY_C12_10', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 10, title: 'Dual Nature of Matter & Radiation', slug: 'dual-nature-matter-radiation', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 22, tags: JSON.stringify(['photoelectric','de broglie','wave-particle duality']), keyTopics: JSON.stringify(['Photoelectric effect','Einstein\'s equation','de Broglie wavelength','Davisson-Germer experiment','Wave-particle duality','Work function']), learningObjectives: JSON.stringify(['Explain photoelectric effect','Calculate de Broglie wavelength','Understand wave-particle duality']), prerequisites: JSON.stringify(['PHY_C12_09']) },
  { chapterId: 'PHY_C12_11', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 11, title: 'Atoms & Nuclei (Modern Physics)', slug: 'atoms-nuclei-modern-physics', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 23, tags: JSON.stringify(['bohr model','nuclear physics','radioactivity','binding energy']), keyTopics: JSON.stringify(['Bohr model of atom','Hydrogen spectrum','Radioactivity','Nuclear reactions','Binding energy','Half-life & decay law']), learningObjectives: JSON.stringify(['Apply Bohr model','Calculate binding energy','Solve radioactivity problems']), prerequisites: JSON.stringify(['PHY_C12_10']) },
  { chapterId: 'PHY_C12_12', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 12, title: 'Semiconductor Devices', slug: 'semiconductor-devices', difficultyLevel: 'foundation', estimatedStudyHours: 12, sortOrder: 24, tags: JSON.stringify(['semiconductor','diode','transistor','logic gates']), keyTopics: JSON.stringify(['p-n junction diode','Zener diode','Transistor (BJT)','Logic gates','Rectifiers','LED & photodiode']), learningObjectives: JSON.stringify(['Understand semiconductor physics','Analyze diode circuits','Apply transistor as switch/amplifier']), prerequisites: JSON.stringify(['PHY_C12_11']) },
  { chapterId: 'PHY_C12_13', subjectId: 'physics', curriculumId: 'ncert_class12', chapterNo: 13, title: 'Communication Systems', slug: 'communication-systems', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 25, tags: JSON.stringify(['modulation','bandwidth','antenna','propagation']), keyTopics: JSON.stringify(['Analog & digital signals','Modulation (AM, FM)','Bandwidth','Propagation of EM waves','Antenna','Satellite communication']), learningObjectives: JSON.stringify(['Understand modulation','Calculate bandwidth','Know propagation modes']), prerequisites: JSON.stringify(['PHY_C12_07']) },

  // ═══════════════════════════════════════════════════════════════════════
  // CHEMISTRY — Class 11 (14 chapters)
  // ═══════════════════════════════════════════════════════════════════════
  { chapterId: 'CHE_C11_01', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 1, title: 'Some Basic Concepts of Chemistry (Mole Concept)', slug: 'mole-concept', difficultyLevel: 'foundation', estimatedStudyHours: 12, sortOrder: 1, tags: JSON.stringify(['mole','stoichiometry','concentration','limiting reagent']), keyTopics: JSON.stringify(['Mole concept','Avogadro\'s number','Stoichiometry','Limiting reagent','Concentration units','Empirical & molecular formula']), learningObjectives: JSON.stringify(['Calculate moles','Solve stoichiometry problems','Determine limiting reagent']), prerequisites: JSON.stringify([]) },
  { chapterId: 'CHE_C11_02', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 2, title: 'Atomic Structure', slug: 'atomic-structure', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 2, tags: JSON.stringify(['quantum numbers','orbitals','electron configuration','bohr']), keyTopics: JSON.stringify(['Bohr model','Quantum numbers','Orbitals (s,p,d,f)','Aufbau principle','Hund\'s rule','Pauli exclusion principle']), learningObjectives: JSON.stringify(['Write electron configurations','Apply quantum numbers','Understand orbital shapes']), prerequisites: JSON.stringify(['CHE_C11_01']) },
  { chapterId: 'CHE_C11_03', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 3, title: 'Classification of Elements & Periodicity', slug: 'periodic-table', difficultyLevel: 'foundation', estimatedStudyHours: 10, sortOrder: 3, tags: JSON.stringify(['periodic table','trends','ionization energy','electronegativity']), keyTopics: JSON.stringify(['Periodic trends','Ionization energy','Electron affinity','Electronegativity','Atomic & ionic radii','Periodic properties']), learningObjectives: JSON.stringify(['Explain periodic trends','Compare element properties','Predict reactivity']), prerequisites: JSON.stringify(['CHE_C11_02']) },
  { chapterId: 'CHE_C11_04', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 4, title: 'Chemical Bonding & Molecular Structure', slug: 'chemical-bonding', difficultyLevel: 'intermediate', estimatedStudyHours: 18, sortOrder: 4, tags: JSON.stringify(['ionic','covalent','vsepr','hybridization','molecular orbital']), keyTopics: JSON.stringify(['Ionic & covalent bonds','VSEPR theory','Hybridization (sp, sp2, sp3)','Molecular orbital theory','Hydrogen bonding','Bond parameters']), learningObjectives: JSON.stringify(['Predict molecular geometry','Apply VSEPR','Understand hybridization']), prerequisites: JSON.stringify(['CHE_C11_02','CHE_C11_03']) },
  { chapterId: 'CHE_C11_05', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 5, title: 'States of Matter', slug: 'states-of-matter', difficultyLevel: 'foundation', estimatedStudyHours: 10, sortOrder: 5, tags: JSON.stringify(['gas laws','ideal gas','van der waals','liquefaction']), keyTopics: JSON.stringify(['Gas laws (Boyle, Charles, Gay-Lussac)','Ideal gas equation','Kinetic molecular theory','Van der Waals equation','Liquefaction of gases','Intermolecular forces']), learningObjectives: JSON.stringify(['Apply gas laws','Use ideal gas equation','Understand real gas behavior']), prerequisites: JSON.stringify(['CHE_C11_01']) },
  { chapterId: 'CHE_C11_06', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 6, title: 'Thermodynamics (Chemistry)', slug: 'thermodynamics-chemistry', difficultyLevel: 'advanced', estimatedStudyHours: 18, sortOrder: 6, tags: JSON.stringify(['enthalpy','entropy','gibbs energy','hess law']), keyTopics: JSON.stringify(['System & surroundings','Enthalpy & Hess\'s law','Entropy','Gibbs free energy','Spontaneity','Bond enthalpies']), learningObjectives: JSON.stringify(['Calculate enthalpy changes','Apply Hess\'s law','Predict spontaneity using Gibbs energy']), prerequisites: JSON.stringify(['CHE_C11_04','CHE_C11_05']) },
  { chapterId: 'CHE_C11_07', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 7, title: 'Equilibrium', slug: 'equilibrium', difficultyLevel: 'advanced', estimatedStudyHours: 20, sortOrder: 7, tags: JSON.stringify(['kc','kp','le chatelier','ionic equilibrium','buffer']), keyTopics: JSON.stringify(['Law of mass action','Kc & Kp','Le Chatelier\'s principle','Ionic equilibrium','pH & buffer solutions','Solubility product']), learningObjectives: JSON.stringify(['Calculate equilibrium constants','Apply Le Chatelier\'s principle','Solve ionic equilibrium problems']), prerequisites: JSON.stringify(['CHE_C11_06']) },
  { chapterId: 'CHE_C11_08', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 8, title: 'Redox Reactions', slug: 'redox-reactions', difficultyLevel: 'intermediate', estimatedStudyHours: 10, sortOrder: 8, tags: JSON.stringify(['oxidation','reduction','oxidation state','balancing redox']), keyTopics: JSON.stringify(['Oxidation & reduction','Oxidation number','Balancing redox equations','Disproportionation','Electrochemical series']), learningObjectives: JSON.stringify(['Assign oxidation numbers','Balance redox equations','Identify oxidizing/reducing agents']), prerequisites: JSON.stringify(['CHE_C11_04']) },
  { chapterId: 'CHE_C11_09', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 9, title: 'Hydrogen', slug: 'hydrogen', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 9, tags: JSON.stringify(['hydrogen','water','hydrides','heavy water']), keyTopics: JSON.stringify(['Isotopes of hydrogen','Preparation of hydrogen','Water structure & properties','Hard & soft water','Hydrides','Heavy water']), learningObjectives: JSON.stringify(['Understand hydrogen chemistry','Know water properties','Classify hydrides']), prerequisites: JSON.stringify(['CHE_C11_04']) },
  { chapterId: 'CHE_C11_10', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 10, title: 's-Block Elements', slug: 's-block-elements', difficultyLevel: 'foundation', estimatedStudyHours: 10, sortOrder: 10, tags: JSON.stringify(['alkali metals','alkaline earth','sodium','calcium']), keyTopics: JSON.stringify(['Group 1 & 2 properties','Anomalous behavior of Li & Be','Important compounds (NaOH, Na2CO3)','Biological importance','Diagonal relationship']), learningObjectives: JSON.stringify(['Compare s-block properties','Know important reactions','Understand diagonal relationship']), prerequisites: JSON.stringify(['CHE_C11_03']) },
  { chapterId: 'CHE_C11_11', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 11, title: 'Organic Chemistry — General Organic Chemistry (GOC)', slug: 'general-organic-chemistry', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 11, tags: JSON.stringify(['inductive effect','resonance','hyperconjugation','reaction mechanisms']), keyTopics: JSON.stringify(['Hybridization in organic compounds','Inductive effect','Resonance','Hyperconjugation','Reaction intermediates (carbocations, carbanions)','Types of organic reactions']), learningObjectives: JSON.stringify(['Predict reaction mechanisms','Apply electronic effects','Identify reaction intermediates']), prerequisites: JSON.stringify(['CHE_C11_04']) },
  { chapterId: 'CHE_C11_12', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 12, title: 'Hydrocarbons', slug: 'hydrocarbons', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 12, tags: JSON.stringify(['alkanes','alkenes','alkynes','benzene','aromaticity']), keyTopics: JSON.stringify(['Alkanes (conformations)','Alkenes (addition reactions)','Alkynes (acidic character)','Benzene & aromaticity','Markovnikov\'s rule','Ozonolysis']), learningObjectives: JSON.stringify(['Predict hydrocarbon reactions','Apply Markovnikov\'s rule','Understand aromaticity']), prerequisites: JSON.stringify(['CHE_C11_11']) },
  { chapterId: 'CHE_C11_13', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 13, title: 'Environmental Chemistry', slug: 'environmental-chemistry', difficultyLevel: 'foundation', estimatedStudyHours: 6, sortOrder: 13, tags: JSON.stringify(['pollution','ozone','greenhouse','acid rain']), keyTopics: JSON.stringify(['Air pollution','Water pollution','Soil pollution','Ozone depletion','Greenhouse effect','Green chemistry']), learningObjectives: JSON.stringify(['Identify pollutants','Understand ozone chemistry','Know greenhouse gases']), prerequisites: JSON.stringify(['CHE_C11_01']) },
  { chapterId: 'CHE_C11_14', subjectId: 'chemistry', curriculumId: 'ncert_class11', chapterNo: 14, title: 'p-Block Elements (Group 13-14)', slug: 'p-block-group-13-14', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 14, tags: JSON.stringify(['boron','carbon','silicon','allotropes']), keyTopics: JSON.stringify(['Group 13 (Boron family)','Group 14 (Carbon family)','Allotropes of carbon','Silicates','Anomalous behavior of B & C','Important compounds']), learningObjectives: JSON.stringify(['Compare group trends','Know important compounds','Understand anomalous behavior']), prerequisites: JSON.stringify(['CHE_C11_03','CHE_C11_04']) },

  // ═══════════════════════════════════════════════════════════════════════
  // CHEMISTRY — Class 12 (14 chapters)
  // ═══════════════════════════════════════════════════════════════════════
  { chapterId: 'CHE_C12_01', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 1, title: 'Solutions', slug: 'solutions', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 15, tags: JSON.stringify(['colligative properties','raoult','osmosis','vant hoff']), keyTopics: JSON.stringify(['Types of solutions','Raoult\'s law','Colligative properties','Osmotic pressure','Van\'t Hoff factor','Abnormal molar mass']), learningObjectives: JSON.stringify(['Apply Raoult\'s law','Calculate colligative properties','Use Van\'t Hoff factor']), prerequisites: JSON.stringify(['CHE_C11_05','CHE_C11_07']) },
  { chapterId: 'CHE_C12_02', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 2, title: 'Electrochemistry', slug: 'electrochemistry', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 16, tags: JSON.stringify(['galvanic cell','electrolysis','nernst','conductance']), keyTopics: JSON.stringify(['Galvanic & electrolytic cells','Standard electrode potential','Nernst equation','Electrolysis & Faraday\'s laws','Conductance & conductivity','Batteries & fuel cells']), learningObjectives: JSON.stringify(['Calculate cell EMF','Apply Nernst equation','Solve electrolysis problems']), prerequisites: JSON.stringify(['CHE_C11_07','CHE_C11_08']) },
  { chapterId: 'CHE_C12_03', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 3, title: 'Chemical Kinetics', slug: 'chemical-kinetics', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 17, tags: JSON.stringify(['rate law','order','activation energy','arrhenius']), keyTopics: JSON.stringify(['Rate of reaction','Rate law & order','Integrated rate equations','Half-life','Activation energy','Arrhenius equation']), learningObjectives: JSON.stringify(['Determine reaction order','Calculate half-life','Apply Arrhenius equation']), prerequisites: JSON.stringify(['CHE_C11_07']) },
  { chapterId: 'CHE_C12_04', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 4, title: 'Surface Chemistry', slug: 'surface-chemistry', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 18, tags: JSON.stringify(['adsorption','colloids','catalysis','emulsion']), keyTopics: JSON.stringify(['Adsorption vs absorption','Catalysis (homogeneous & heterogeneous)','Colloids & sols','Emulsions','Tyndall effect','Coagulation']), learningObjectives: JSON.stringify(['Distinguish adsorption types','Understand colloid properties','Explain catalysis mechanisms']), prerequisites: JSON.stringify(['CHE_C11_05']) },
  { chapterId: 'CHE_C12_05', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 5, title: 'p-Block Elements (Group 15-18)', slug: 'p-block-group-15-18', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 19, tags: JSON.stringify(['nitrogen','oxygen','halogens','noble gases','ozone']), keyTopics: JSON.stringify(['Group 15 (N family)','Group 16 (O family)','Group 17 (Halogens)','Group 18 (Noble gases)','Oxoacids of N, P, S, Cl','Interhalogen compounds']), learningObjectives: JSON.stringify(['Compare group properties','Know oxoacid structures','Understand halogen chemistry']), prerequisites: JSON.stringify(['CHE_C11_14']) },
  { chapterId: 'CHE_C12_06', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 6, title: 'd & f Block Elements', slug: 'd-f-block-elements', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 20, tags: JSON.stringify(['transition metals','lanthanides','actinides','oxidation states']), keyTopics: JSON.stringify(['Transition metal properties','Variable oxidation states','Complex formation','Lanthanide contraction','Actinides','Important compounds (KMnO4, K2Cr2O7)']), learningObjectives: JSON.stringify(['Explain transition metal properties','Understand lanthanide contraction','Know important reactions']), prerequisites: JSON.stringify(['CHE_C11_03','CHE_C11_08']) },
  { chapterId: 'CHE_C12_07', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 7, title: 'Coordination Compounds', slug: 'coordination-compounds', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 21, tags: JSON.stringify(['ligands','CFSE','isomerism','coordination number']), keyTopics: JSON.stringify(['Werner\'s theory','IUPAC nomenclature','Crystal field theory','Isomerism in coordination compounds','Stability of complexes','Organometallic compounds']), learningObjectives: JSON.stringify(['Name coordination compounds','Apply crystal field theory','Identify isomers']), prerequisites: JSON.stringify(['CHE_C12_06']) },
  { chapterId: 'CHE_C12_08', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 8, title: 'Haloalkanes & Haloarenes', slug: 'haloalkanes-haloarenes', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 22, tags: JSON.stringify(['SN1','SN2','elimination','nucleophilic substitution']), keyTopics: JSON.stringify(['Preparation of haloalkanes','SN1 & SN2 mechanisms','E1 & E2 elimination','Reactivity order','Haloarenes','Grignard reagent']), learningObjectives: JSON.stringify(['Predict SN1 vs SN2','Understand elimination reactions','Apply Grignard reactions']), prerequisites: JSON.stringify(['CHE_C11_11','CHE_C11_12']) },
  { chapterId: 'CHE_C12_09', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 9, title: 'Alcohols, Phenols & Ethers', slug: 'alcohols-phenols-ethers', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 23, tags: JSON.stringify(['alcohol','phenol','ether','lucas test']), keyTopics: JSON.stringify(['Classification of alcohols','Reactions of alcohols','Phenol acidity','Ether preparation','Lucas test','Williamson synthesis']), learningObjectives: JSON.stringify(['Predict alcohol reactions','Explain phenol acidity','Synthesize ethers']), prerequisites: JSON.stringify(['CHE_C12_08']) },
  { chapterId: 'CHE_C12_10', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 10, title: 'Aldehydes, Ketones & Carboxylic Acids', slug: 'aldehydes-ketones-carboxylic-acids', difficultyLevel: 'advanced', estimatedStudyHours: 18, sortOrder: 24, tags: JSON.stringify(['aldol','cannizzaro','nucleophilic addition','carboxylic acid']), keyTopics: JSON.stringify(['Nucleophilic addition reactions','Aldol condensation','Cannizzaro reaction','Clemmensen reduction','Carboxylic acid derivatives','Hell-Volhard-Zelinsky reaction']), learningObjectives: JSON.stringify(['Predict carbonyl reactions','Apply named reactions','Synthesize carboxylic acids']), prerequisites: JSON.stringify(['CHE_C12_09']) },
  { chapterId: 'CHE_C12_11', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 11, title: 'Amines & Diazonium Salts', slug: 'amines-diazonium', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 25, tags: JSON.stringify(['amines','basicity','diazonium','coupling reaction']), keyTopics: JSON.stringify(['Classification of amines','Basicity of amines','Preparation of amines','Diazonium salts','Coupling reactions','Gabriel synthesis']), learningObjectives: JSON.stringify(['Compare amine basicities','Understand diazonium chemistry','Apply Gabriel synthesis']), prerequisites: JSON.stringify(['CHE_C12_10']) },
  { chapterId: 'CHE_C12_12', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 12, title: 'Biomolecules', slug: 'biomolecules', difficultyLevel: 'foundation', estimatedStudyHours: 10, sortOrder: 26, tags: JSON.stringify(['carbohydrates','proteins','nucleic acids','vitamins']), keyTopics: JSON.stringify(['Carbohydrates (mono, di, polysaccharides)','Proteins & amino acids','Enzymes','Nucleic acids (DNA, RNA)','Vitamins','Hormones']), learningObjectives: JSON.stringify(['Classify biomolecules','Understand enzyme action','Know nucleic acid structure']), prerequisites: JSON.stringify(['CHE_C12_10']) },
  { chapterId: 'CHE_C12_13', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 13, title: 'Polymers', slug: 'polymers', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 27, tags: JSON.stringify(['addition polymer','condensation polymer','rubber','plastic']), keyTopics: JSON.stringify(['Addition & condensation polymerization','Natural & synthetic rubber','Plastics','Biodegradable polymers','Copolymers','Important polymers (nylon, dacron, teflon)']), learningObjectives: JSON.stringify(['Classify polymers','Understand polymerization','Know commercial polymers']), prerequisites: JSON.stringify(['CHE_C11_12']) },
  { chapterId: 'CHE_C12_14', subjectId: 'chemistry', curriculumId: 'ncert_class12', chapterNo: 14, title: 'Chemistry in Everyday Life', slug: 'chemistry-everyday-life', difficultyLevel: 'foundation', estimatedStudyHours: 6, sortOrder: 28, tags: JSON.stringify(['drugs','food additives','cleansing agents','chemicals']), keyTopics: JSON.stringify(['Drugs & medicines','Analgesics, antibiotics, antiseptics','Food additives & preservatives','Soaps & detergents','Rocket propellants']), learningObjectives: JSON.stringify(['Classify drugs','Know food chemistry','Understand cleansing agents']), prerequisites: JSON.stringify(['CHE_C12_12']) },

  // ═══════════════════════════════════════════════════════════════════════
  // MATHEMATICS — Class 11 (14 chapters)
  // ═══════════════════════════════════════════════════════════════════════
  { chapterId: 'MAT_C11_01', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 1, title: 'Sets, Relations & Functions', slug: 'sets-relations-functions', difficultyLevel: 'foundation', estimatedStudyHours: 12, sortOrder: 1, tags: JSON.stringify(['sets','venn diagrams','functions','domain range']), keyTopics: JSON.stringify(['Set operations','Venn diagrams','Types of relations','Types of functions','Composition of functions','Inverse functions']), learningObjectives: JSON.stringify(['Perform set operations','Classify functions','Find domain and range']), prerequisites: JSON.stringify([]) },
  { chapterId: 'MAT_C11_02', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 2, title: 'Trigonometry', slug: 'trigonometry', difficultyLevel: 'intermediate', estimatedStudyHours: 18, sortOrder: 2, tags: JSON.stringify(['trigonometric ratios','identities','inverse trig','equations']), keyTopics: JSON.stringify(['Trigonometric ratios & identities','Allied angles','Compound angle formulas','Multiple angle formulas','Inverse trigonometric functions','Trigonometric equations']), learningObjectives: JSON.stringify(['Prove trigonometric identities','Solve trigonometric equations','Apply compound angle formulas']), prerequisites: JSON.stringify(['MAT_C11_01']) },
  { chapterId: 'MAT_C11_03', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 3, title: 'Complex Numbers', slug: 'complex-numbers', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 3, tags: JSON.stringify(['complex numbers','argand plane','modulus','argument','de moivre']), keyTopics: JSON.stringify(['Algebra of complex numbers','Argand plane','Modulus & argument','Polar form','De Moivre\'s theorem','Cube roots of unity']), learningObjectives: JSON.stringify(['Perform complex arithmetic','Use De Moivre\'s theorem','Find roots of complex numbers']), prerequisites: JSON.stringify(['MAT_C11_01']) },
  { chapterId: 'MAT_C11_04', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 4, title: 'Quadratic Equations & Inequalities', slug: 'quadratic-equations', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 4, tags: JSON.stringify(['quadratic','discriminant','roots','inequalities']), keyTopics: JSON.stringify(['Quadratic formula','Nature of roots (discriminant)','Vieta\'s formulas','Quadratic inequalities','Location of roots','Transformation of equations']), learningObjectives: JSON.stringify(['Solve quadratic equations','Analyze root nature','Solve quadratic inequalities']), prerequisites: JSON.stringify(['MAT_C11_03']) },
  { chapterId: 'MAT_C11_05', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 5, title: 'Sequences & Series', slug: 'sequences-series', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 5, tags: JSON.stringify(['AP','GP','HP','AGP','sum of series']), keyTopics: JSON.stringify(['Arithmetic Progression (AP)','Geometric Progression (GP)','Harmonic Progression (HP)','Arithmetic-Geometric Progression','Sum of special series','Telescoping series']), learningObjectives: JSON.stringify(['Find nth term and sum','Solve AP/GP problems','Apply special series formulas']), prerequisites: JSON.stringify(['MAT_C11_04']) },
  { chapterId: 'MAT_C11_06', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 6, title: 'Permutations & Combinations', slug: 'permutations-combinations', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 6, tags: JSON.stringify(['factorial','permutation','combination','binomial theorem']), keyTopics: JSON.stringify(['Fundamental counting principle','Permutations (nPr)','Combinations (nCr)','Circular permutations','Binomial theorem','Properties of binomial coefficients']), learningObjectives: JSON.stringify(['Apply counting principles','Solve permutation/combination problems','Use binomial theorem']), prerequisites: JSON.stringify(['MAT_C11_05']) },
  { chapterId: 'MAT_C11_07', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 7, title: 'Straight Lines & Pair of Lines', slug: 'straight-lines', difficultyLevel: 'foundation', estimatedStudyHours: 14, sortOrder: 7, tags: JSON.stringify(['slope','intercept','distance','angle between lines']), keyTopics: JSON.stringify(['Slope of a line','Various forms of line equation','Distance from a point to a line','Angle between two lines','Pair of straight lines','Family of lines']), learningObjectives: JSON.stringify(['Write line equations','Calculate distances','Find angle between lines']), prerequisites: JSON.stringify(['MAT_C11_01']) },
  { chapterId: 'MAT_C11_08', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 8, title: 'Circles', slug: 'circles', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 8, tags: JSON.stringify(['circle equation','tangent','chord','radical axis']), keyTopics: JSON.stringify(['Standard & general equation of circle','Tangent to a circle','Chord of contact','Radical axis','Family of circles','Power of a point']), learningObjectives: JSON.stringify(['Write circle equations','Find tangents','Apply radical axis']), prerequisites: JSON.stringify(['MAT_C11_07']) },
  { chapterId: 'MAT_C11_09', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 9, title: 'Conic Sections (Parabola, Ellipse, Hyperbola)', slug: 'conic-sections', difficultyLevel: 'advanced', estimatedStudyHours: 20, sortOrder: 9, tags: JSON.stringify(['parabola','ellipse','hyperbola','focus','directrix']), keyTopics: JSON.stringify(['Parabola (standard forms)','Ellipse (standard forms)','Hyperbola (standard forms)','Tangent & normal to conics','Chord of contact','Asymptotes of hyperbola']), learningObjectives: JSON.stringify(['Identify conic sections','Write equations of conics','Find tangents and normals']), prerequisites: JSON.stringify(['MAT_C11_08']) },
  { chapterId: 'MAT_C11_10', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 10, title: 'Limits & Derivatives (Differential Calculus Intro)', slug: 'limits-derivatives', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 10, tags: JSON.stringify(['limits','continuity','derivatives','differentiation rules']), keyTopics: JSON.stringify(['Concept of limits','Standard limits','Continuity & differentiability','First principles of differentiation','Differentiation rules','Derivatives of standard functions']), learningObjectives: JSON.stringify(['Evaluate limits','Check continuity','Differentiate functions']), prerequisites: JSON.stringify(['MAT_C11_02','MAT_C11_04']) },
  { chapterId: 'MAT_C11_11', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 11, title: 'Mathematical Induction', slug: 'mathematical-induction', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 11, tags: JSON.stringify(['induction','proof','principle of mathematical induction']), keyTopics: JSON.stringify(['Principle of mathematical induction','Weak & strong induction','Proving divisibility','Proving inequalities','Proving series formulas']), learningObjectives: JSON.stringify(['Apply PMI correctly','Prove series formulas','Prove divisibility results']), prerequisites: JSON.stringify(['MAT_C11_05']) },
  { chapterId: 'MAT_C11_12', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 12, title: 'Statistics', slug: 'statistics', difficultyLevel: 'foundation', estimatedStudyHours: 8, sortOrder: 12, tags: JSON.stringify(['mean','variance','standard deviation','dispersion']), keyTopics: JSON.stringify(['Measures of central tendency','Mean, median, mode','Variance & standard deviation','Coefficient of variation','Frequency distribution']), learningObjectives: JSON.stringify(['Calculate statistical measures','Find variance and SD','Compare dispersions']), prerequisites: JSON.stringify(['MAT_C11_01']) },
  { chapterId: 'MAT_C11_13', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 13, title: 'Mathematical Reasoning', slug: 'mathematical-reasoning', difficultyLevel: 'foundation', estimatedStudyHours: 6, sortOrder: 13, tags: JSON.stringify(['logic','statements','connectives','quantifiers']), keyTopics: JSON.stringify(['Statements & truth values','Logical connectives','Tautology & contradiction','Quantifiers','Implications & contrapositive']), learningObjectives: JSON.stringify(['Identify logical statements','Construct truth tables','Apply logical reasoning']), prerequisites: JSON.stringify(['MAT_C11_01']) },
  { chapterId: 'MAT_C11_14', subjectId: 'mathematics', curriculumId: 'ncert_class11', chapterNo: 14, title: 'Probability (Basic)', slug: 'probability-basic', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 14, tags: JSON.stringify(['probability','events','sample space','conditional probability']), keyTopics: JSON.stringify(['Sample space & events','Classical probability','Addition theorem','Conditional probability','Multiplication theorem','Independent events']), learningObjectives: JSON.stringify(['Calculate probabilities','Apply addition/multiplication theorems','Solve conditional probability problems']), prerequisites: JSON.stringify(['MAT_C11_06']) },

  // ═══════════════════════════════════════════════════════════════════════
  // MATHEMATICS — Class 12 (13 chapters)
  // ═══════════════════════════════════════════════════════════════════════
  { chapterId: 'MAT_C12_01', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 1, title: 'Inverse Trigonometric Functions', slug: 'inverse-trigonometric-functions', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 15, tags: JSON.stringify(['arcsin','arccos','arctan','principal value']), keyTopics: JSON.stringify(['Domain & range of inverse trig functions','Principal value branch','Properties of inverse trig functions','Simplification of expressions','Equations involving inverse trig']), learningObjectives: JSON.stringify(['Find principal values','Apply inverse trig properties','Solve inverse trig equations']), prerequisites: JSON.stringify(['MAT_C11_02']) },
  { chapterId: 'MAT_C12_02', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 2, title: 'Matrices & Determinants', slug: 'matrices-determinants', difficultyLevel: 'foundation', estimatedStudyHours: 16, sortOrder: 16, tags: JSON.stringify(['matrix operations','determinant','inverse matrix','cramer rule']), keyTopics: JSON.stringify(['Matrix operations','Types of matrices','Determinant properties','Cofactors & adjoint','Inverse of matrix','Cramer\'s rule']), learningObjectives: JSON.stringify(['Perform matrix operations','Calculate determinants','Solve systems using matrices']), prerequisites: JSON.stringify(['MAT_C11_04']) },
  { chapterId: 'MAT_C12_03', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 3, title: 'Continuity & Differentiability', slug: 'continuity-differentiability', difficultyLevel: 'intermediate', estimatedStudyHours: 16, sortOrder: 17, tags: JSON.stringify(['continuity','differentiability','chain rule','implicit differentiation']), keyTopics: JSON.stringify(['Continuity at a point','Differentiability','Chain rule','Implicit differentiation','Parametric differentiation','Higher order derivatives']), learningObjectives: JSON.stringify(['Test continuity and differentiability','Apply chain rule','Differentiate implicit functions']), prerequisites: JSON.stringify(['MAT_C11_10']) },
  { chapterId: 'MAT_C12_04', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 4, title: 'Applications of Derivatives', slug: 'applications-derivatives', difficultyLevel: 'advanced', estimatedStudyHours: 18, sortOrder: 18, tags: JSON.stringify(['maxima minima','tangent normal','rate of change','rolle mean value']), keyTopics: JSON.stringify(['Rate of change','Tangent & normal to curves','Increasing & decreasing functions','Maxima & minima','Rolle\'s theorem','Mean value theorem']), learningObjectives: JSON.stringify(['Find maxima and minima','Write tangent/normal equations','Apply mean value theorems']), prerequisites: JSON.stringify(['MAT_C12_03']) },
  { chapterId: 'MAT_C12_05', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 5, title: 'Indefinite Integration', slug: 'indefinite-integration', difficultyLevel: 'advanced', estimatedStudyHours: 20, sortOrder: 19, tags: JSON.stringify(['integration','substitution','partial fractions','by parts']), keyTopics: JSON.stringify(['Standard integrals','Integration by substitution','Integration by parts','Partial fractions','Integration of rational functions','Special integrals']), learningObjectives: JSON.stringify(['Apply integration techniques','Use partial fractions','Integrate by parts']), prerequisites: JSON.stringify(['MAT_C12_03']) },
  { chapterId: 'MAT_C12_06', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 6, title: 'Definite Integration & Area Under Curves', slug: 'definite-integration-area', difficultyLevel: 'advanced', estimatedStudyHours: 18, sortOrder: 20, tags: JSON.stringify(['definite integral','fundamental theorem','area','properties of definite integrals']), keyTopics: JSON.stringify(['Fundamental theorem of calculus','Properties of definite integrals','Definite integration by substitution','Area between curves','Leibniz rule','Gamma function basics']), learningObjectives: JSON.stringify(['Evaluate definite integrals','Apply integral properties','Calculate areas']), prerequisites: JSON.stringify(['MAT_C12_05']) },
  { chapterId: 'MAT_C12_07', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 7, title: 'Differential Equations', slug: 'differential-equations', difficultyLevel: 'advanced', estimatedStudyHours: 16, sortOrder: 21, tags: JSON.stringify(['ODE','variable separable','linear ODE','homogeneous']), keyTopics: JSON.stringify(['Order & degree','Variable separable method','Homogeneous equations','Linear differential equations','Bernoulli\'s equation','Applications of ODEs']), learningObjectives: JSON.stringify(['Classify differential equations','Solve variable separable ODEs','Solve linear ODEs']), prerequisites: JSON.stringify(['MAT_C12_06']) },
  { chapterId: 'MAT_C12_08', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 8, title: 'Vector Algebra', slug: 'vector-algebra', difficultyLevel: 'intermediate', estimatedStudyHours: 14, sortOrder: 22, tags: JSON.stringify(['vectors','dot product','cross product','scalar triple product']), keyTopics: JSON.stringify(['Types of vectors','Addition & scalar multiplication','Dot product & cross product','Scalar triple product','Vector triple product','Applications of vectors']), learningObjectives: JSON.stringify(['Perform vector operations','Calculate dot and cross products','Apply vector triple product']), prerequisites: JSON.stringify(['MAT_C11_07']) },
  { chapterId: 'MAT_C12_09', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 9, title: '3D Geometry', slug: '3d-geometry', difficultyLevel: 'advanced', estimatedStudyHours: 18, sortOrder: 23, tags: JSON.stringify(['3d coordinates','direction cosines','line in 3d','plane in 3d']), keyTopics: JSON.stringify(['Direction cosines & ratios','Equation of line in 3D','Equation of plane','Angle between line & plane','Distance from point to plane','Skew lines']), learningObjectives: JSON.stringify(['Write 3D line equations','Find plane equations','Calculate distances in 3D']), prerequisites: JSON.stringify(['MAT_C12_08']) },
  { chapterId: 'MAT_C12_10', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 10, title: 'Probability (Advanced)', slug: 'probability-advanced', difficultyLevel: 'advanced', estimatedStudyHours: 16, sortOrder: 24, tags: JSON.stringify(['bayes theorem','random variable','binomial distribution','expected value']), keyTopics: JSON.stringify(['Conditional probability','Bayes\' theorem','Random variables','Probability distributions','Binomial distribution','Expected value & variance']), learningObjectives: JSON.stringify(['Apply Bayes\' theorem','Define random variables','Solve binomial distribution problems']), prerequisites: JSON.stringify(['MAT_C11_14']) },
  { chapterId: 'MAT_C12_11', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 11, title: 'Linear Programming', slug: 'linear-programming', difficultyLevel: 'foundation', estimatedStudyHours: 10, sortOrder: 25, tags: JSON.stringify(['LPP','feasible region','objective function','corner point']), keyTopics: JSON.stringify(['Linear programming problem formulation','Feasible region','Corner point method','Optimal solution','Graphical method','Applications of LPP']), learningObjectives: JSON.stringify(['Formulate LPP','Find feasible region','Determine optimal solution']), prerequisites: JSON.stringify(['MAT_C11_07']) },
  { chapterId: 'MAT_C12_12', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 12, title: 'Relations & Functions (Advanced)', slug: 'relations-functions-advanced', difficultyLevel: 'intermediate', estimatedStudyHours: 10, sortOrder: 26, tags: JSON.stringify(['equivalence relation','bijection','composition','inverse function']), keyTopics: JSON.stringify(['Equivalence relations','One-one & onto functions','Bijections','Composition of functions','Inverse functions','Binary operations']), learningObjectives: JSON.stringify(['Verify equivalence relations','Prove bijectivity','Find inverse functions']), prerequisites: JSON.stringify(['MAT_C11_01']) },
  { chapterId: 'MAT_C12_13', subjectId: 'mathematics', curriculumId: 'ncert_class12', chapterNo: 13, title: 'Number Theory & Miscellaneous Algebra', slug: 'number-theory-misc-algebra', difficultyLevel: 'intermediate', estimatedStudyHours: 12, sortOrder: 27, tags: JSON.stringify(['number theory','divisibility','modular arithmetic','functional equations']), keyTopics: JSON.stringify(['Divisibility & GCD','Modular arithmetic','Functional equations','Inequalities (AM-GM, Cauchy-Schwarz)','Integer problems','JEE Advanced special topics']), learningObjectives: JSON.stringify(['Apply divisibility rules','Solve modular arithmetic','Use AM-GM inequality']), prerequisites: JSON.stringify(['MAT_C11_04','MAT_C11_05']) },
];

for (const ch of chapters) {
  const { tags, keyTopics, learningObjectives, prerequisites, ...rest } = ch;
  await conn.execute(
    `INSERT INTO chapters (chapterId, subjectId, curriculumId, chapterNo, title, slug, difficultyLevel, estimatedStudyHours, sortOrder, tags, keyTopics, learningObjectives, prerequisites, isActive)
     VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1)
     ON DUPLICATE KEY UPDATE title=VALUES(title), slug=VALUES(slug), difficultyLevel=VALUES(difficultyLevel), estimatedStudyHours=VALUES(estimatedStudyHours), sortOrder=VALUES(sortOrder), tags=VALUES(tags), keyTopics=VALUES(keyTopics), learningObjectives=VALUES(learningObjectives), prerequisites=VALUES(prerequisites)`,
    [rest.chapterId, rest.subjectId, rest.curriculumId, rest.chapterNo, rest.title, rest.slug, rest.difficultyLevel, rest.estimatedStudyHours, rest.sortOrder, tags, keyTopics, learningObjectives, prerequisites]
  );
}
console.log(`Seeded ${chapters.length} chapters`);

// ─── 6. Exam-Chapter Weightage ─────────────────────────────────────────────────
console.log('Seeding exam-chapter weightage...');
// Weightage data from planning document
const weightageData = {
  // Physics High Weightage
  'PHY_C11_02': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // Kinematics
  'PHY_C11_03': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // Laws of Motion
  'PHY_C11_04': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'critical' }, // WEP
  'PHY_C11_05': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'critical' }, // Rotation (tough)
  'PHY_C12_02': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // Current Electricity
  'PHY_C12_05': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'critical' }, // EMI (tough)
  'PHY_C12_11': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'critical' }, // Modern Physics (easy)
  'PHY_C12_08': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'high' },    // Ray Optics
  'PHY_C12_09': { jee_main: 'medium', jee_advanced: 'high', avgQ: 2.5, importance: 'high' },  // Wave Optics
  // Physics Medium
  'PHY_C11_08': { jee_main: 'medium', jee_advanced: 'medium', avgQ: 2.0, importance: 'medium' }, // Thermodynamics
  'PHY_C11_10': { jee_main: 'medium', jee_advanced: 'high', avgQ: 2.5, importance: 'high' },  // SHM (tough)
  'PHY_C11_11': { jee_main: 'medium', jee_advanced: 'medium', avgQ: 2.0, importance: 'medium' }, // Waves
  'PHY_C12_01': { jee_main: 'medium', jee_advanced: 'high', avgQ: 2.5, importance: 'high' },  // Electrostatics
  // Physics Low
  'PHY_C11_01': { jee_main: 'low', jee_advanced: 'low', avgQ: 1.0, importance: 'low' },       // Units
  'PHY_C12_12': { jee_main: 'low', jee_advanced: 'low', avgQ: 1.5, importance: 'low' },       // Semiconductors (easy)

  // Chemistry High Weightage
  'CHE_C11_11': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // GOC
  'CHE_C11_12': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'critical' }, // Hydrocarbons
  'CHE_C12_07': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'critical' }, // Coordination Compounds
  'CHE_C11_04': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'critical' }, // Chemical Bonding
  'CHE_C11_07': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // Equilibrium (tough)
  'CHE_C12_10': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.0, importance: 'high' },    // Aldehydes/Ketones
  // Chemistry Medium
  'CHE_C11_06': { jee_main: 'medium', jee_advanced: 'high', avgQ: 2.5, importance: 'high' },  // Thermodynamics (tough)
  'CHE_C12_02': { jee_main: 'medium', jee_advanced: 'medium', avgQ: 2.5, importance: 'medium' }, // Electrochemistry
  'CHE_C12_05': { jee_main: 'medium', jee_advanced: 'medium', avgQ: 2.0, importance: 'medium' }, // p-Block 15-18
  // Chemistry Low
  'CHE_C11_13': { jee_main: 'low', jee_advanced: 'low', avgQ: 1.0, importance: 'low' },       // Environmental (easy)
  'CHE_C12_04': { jee_main: 'low', jee_advanced: 'low', avgQ: 1.0, importance: 'low' },       // Surface Chemistry (easy)
  'CHE_C12_12': { jee_main: 'low', jee_advanced: 'low', avgQ: 1.5, importance: 'low' },       // Biomolecules (easy)

  // Mathematics High Weightage
  'MAT_C12_05': { jee_main: 'high', jee_advanced: 'high', avgQ: 4.0, importance: 'critical' }, // Indefinite Integration (tough)
  'MAT_C12_06': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // Definite Integration (tough)
  'MAT_C12_04': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // Applications of Derivatives
  'MAT_C11_09': { jee_main: 'high', jee_advanced: 'high', avgQ: 3.5, importance: 'critical' }, // Conic Sections
  'MAT_C12_02': { jee_main: 'high', jee_advanced: 'medium', avgQ: 3.0, importance: 'high' },  // Matrices (easy)
  // Mathematics Medium
  'MAT_C11_03': { jee_main: 'medium', jee_advanced: 'high', avgQ: 2.5, importance: 'high' },  // Complex Numbers
  'MAT_C12_10': { jee_main: 'medium', jee_advanced: 'high', avgQ: 2.5, importance: 'high' },  // Probability (tough)
  'MAT_C11_04': { jee_main: 'medium', jee_advanced: 'medium', avgQ: 2.0, importance: 'medium' }, // Quadratics
  // Mathematics Low
  'MAT_C11_13': { jee_main: 'low', jee_advanced: 'low', avgQ: 1.0, importance: 'low' },       // Mathematical Reasoning
  'MAT_C11_12': { jee_main: 'low', jee_advanced: 'low', avgQ: 1.0, importance: 'low' },       // Statistics
  'MAT_C11_07': { jee_main: 'low', jee_advanced: 'medium', avgQ: 1.5, importance: 'medium' }, // Straight Lines (easy)
};

for (const [chapterId, data] of Object.entries(weightageData)) {
  for (const examId of ['jee_main', 'jee_advanced']) {
    await conn.execute(
      `INSERT INTO exam_chapter_weightage (examId, chapterId, weightagePercent, avgQuestionsPerYear, importanceLevel, notes)
       VALUES (?,?,?,?,?,?)
       ON DUPLICATE KEY UPDATE weightagePercent=VALUES(weightagePercent), avgQuestionsPerYear=VALUES(avgQuestionsPerYear), importanceLevel=VALUES(importanceLevel)`,
      [examId, chapterId, data[examId], data.avgQ, data.importance, `Weightage: ${data[examId]}, Avg ${data.avgQ} questions/year`]
    );
  }
}
console.log('Seeded weightage data');

await conn.end();
console.log('\n✅ Seed complete! All 80 chapters + registry data inserted.');
